# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.TextField(max_length=500),
        ),
    ]
