# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0002_auto_20160411_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('roll_no', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(max_length=500)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(default='Tamil Nadu', editable=False, max_length=50)),
                ('photo', models.ImageField(upload_to='/tmp')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.School')),
            ],
        ),
    ]
