# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='/tmp'),
        ),
    ]
