# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0004_auto_20160412_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.CharField(max_length=10)),
                ('parent_type', models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Guardian', 'Guardian')], max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=500)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(default='Tamil Nadu', editable=False, max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='/tmp')),
                ('school_id', models.ManyToManyField(to='ats.School')),
            ],
        ),
    ]
