# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0005_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ats.Parent'),
            preserve_default=False,
        ),
    ]
