# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0006_student_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='parent_id',
        ),
    ]
