# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0007_remove_parent_parent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set([('standard', 'section')]),
        ),
    ]
