# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0008_auto_20160415_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='standard',
            field=models.CharField(max_length=2),
        ),
    ]
