# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0010_class_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.School'),
        ),
    ]
