# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0011_auto_20160418_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Dr.', 'Dr.'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Miss.', 'Miss.')], default='Mr.', max_length=5)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('staff_id', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('staff_type', models.CharField(choices=[('T', 'TEACHING'), ('NT', 'NON-TEACHING'), ('P', 'PRINCIPAL')], max_length=20)),
                ('dob', models.DateField()),
                ('doj', models.DateField()),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=500)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(default='Tamil Nadu', editable=False, max_length=50)),
                ('country', models.CharField(default='India', editable=False, max_length=30)),
                ('experience', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='/tmp')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='contact',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='state',
        ),
        migrations.AddField(
            model_name='class',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='country',
            field=models.CharField(default='India', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='parent',
            name='title',
            field=models.CharField(choices=[('Dr.', 'Dr.'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Miss.', 'Miss.')], default='Mr.', max_length=5),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name of school'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set([('standard', 'section', 'school_id')]),
        ),
        migrations.AddField(
            model_name='subject',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.School'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set([('subject_id', 'subject_name', 'school_id')]),
        ),
    ]
