# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attn', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=2)),
                ('section', models.CharField(max_length=1)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_type', models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Guardian', 'Guardian')], max_length=20)),
                ('title', models.CharField(choices=[('Dr.', 'Dr.'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Miss.', 'Miss.')], default='Mr.', max_length=5)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=500)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(default='Tamil Nadu', editable=False, max_length=50)),
                ('country', models.CharField(default='India', editable=False, max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='/tmp')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name of school')),
                ('board', models.CharField(choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('State Board Tamil', 'State Board'), ('State Board Matriculation', 'State Board Matriculation')], max_length=30)),
                ('address', models.TextField(max_length=500)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(default='Tamil Nadu', editable=False, max_length=50)),
                ('country', models.CharField(default='India', editable=False, max_length=30)),
                ('phone1', models.CharField(max_length=30)),
                ('phone2', models.CharField(blank=True, max_length=30, null=True)),
                ('fax', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Dr.', 'Dr.'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Miss.', 'Miss.')], default='Mr.', max_length=5)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('staff_id', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('staff_type', models.CharField(choices=[('T', 'TEACHING'), ('NT', 'NON-TEACHING'), ('P', 'PRINCIPAL')], max_length=20)),
                ('dob', models.DateField()),
                ('doj', models.DateField()),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=500)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(default='Tamil Nadu', editable=False, max_length=50)),
                ('country', models.CharField(default='India', editable=False, max_length=30)),
                ('experience', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='/tmp')),
                ('class_id', models.ManyToManyField(to='utils.Class')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.School')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Dr.', 'Dr.'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Miss.', 'Miss.')], default='Mr.', max_length=5)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('roll_no', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(default='Tamil Nadu', editable=False, max_length=50)),
                ('country', models.CharField(default='India', editable=False, max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='/tmp')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Class')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Parent')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.School')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=100)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.School')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_id', models.IntegerField()),
                ('start_month', models.CharField(max_length=20)),
                ('end_month', models.CharField(max_length=20)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.School')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='subject_id',
            field=models.ManyToManyField(to='utils.Subject'),
        ),
        migrations.AddField(
            model_name='parent',
            name='school_id',
            field=models.ManyToManyField(to='utils.School'),
        ),
        migrations.AddField(
            model_name='class',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.School'),
        ),
        migrations.AddField(
            model_name='attn',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Class'),
        ),
        migrations.AddField(
            model_name='attn',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.School'),
        ),
        migrations.AddField(
            model_name='attn',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Student'),
        ),
        migrations.AddField(
            model_name='attn',
            name='subject_id',
            field=models.ManyToManyField(to='utils.Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set([('subject_id', 'subject_name', 'school_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set([('standard', 'section', 'school_id')]),
        ),
    ]
